import org.jointheleague.graphical.robot.Robot;

public class RobotSquare {
	public static void main(String[] args) {
		int time = 26;
		Robot bot = new Robot();
bot.moveTo(400,400);
	// x between 400 & 600
	// y between 200 and 400

		bot.penDown();
		bot.setSpeed(10);
		bot.setPenColor(100, 50, 110);
		int speed = 10;
		for (int i = 0; i < 4; i = i + 1) {

			bot.move(200);
			bot.turn(90);
		}
		
		bot.moveTo(500, 400);
		bot.penUp();
		bot.penDown();
		bot.setRandomPenColor();
		bot.move(20);
				bot.penDown();
		bot.setRandomPenColor();
	bot.move(200);
	bot.turn(90);
	bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
	bot.penUp();
	bot.penDown();
	bot.setRandomPenColor();
	bot.move(200);
	bot.turn(90);
	bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
	bot.penUp();
	bot.penDown();
	bot.setRandomPenColor();
	bot.move(200);
	bot.turn(90);
	bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
	bot.penUp();
	bot.penDown();
	bot.setRandomPenColor();
	bot.move(200);
	bot.turn(90);
	bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));		bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));	bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));	bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.moveTo(100, 100);
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));
bot.penUp();
bot.penDown();
bot.setRandomPenColor();
bot.move(200);
bot.turn(90);
bot.moveTo((int)(200*Math.random()), (int)(200*Math.random()));




	

	}
}